### ISSUE TITLE
Infinite shotgun ammo

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1097]
Shown in this video https://youtu.be/_TaWJz14NF4?t=315

To reproduce:
Pickup an empty shotgun and less than 6 shells, then reload.

**Comment by Z1Meme** [comment]
Can't reproduce.

**Comment by QuentinGruber** [comment]
Yep it's fixed now it seems

**Comment by QuentinGruber** [comment]
sorry mistake

**Comment by Z1Meme** [comment]
@QuentinGruber It just happend to me so it's actually not fixed lol

**Comment by QuentinGruber** [comment]
> @QuentinGruber It just happened to me so it's actually not fixed lol

Ok aha it happened to me on an old branch so it's why i've reclose it
